# Shared path filter definitions
# Used by path-filter.yml workflow for both PR-level and push-level checks
#
# NOTE: Do not add gitignored paths here (android/, ios/, pdb-*/, .env)
# They will never trigger since they're never committed.

shell:
  - '**/*.sh'
  - '.husky/**'
  - '.claude/hooks/**'

app:
  # Source code (excluding test files)
  - 'app/**'
  - 'core/**'
  - 'ui/**'
  - 'infra/**'
  - '!**/*.spec.ts'
  - '!**/*.test.ts'
  - '!**/_tests_/**'
  - '!**/fixtures/**'
  - '!**/data-builders/**'
  - '!**/in-memory.*'
  # Config files that affect the build (NOT test config)
  - 'app.config.js'
  - 'package.json'
  - '!vitest.config.js'
  - 'package-lock.json'
  - 'tsconfig.json'
  - 'babel.config.cjs'
  - 'metro.config.cjs'
  - 'eas.json'
  - 'schema.prisma'
  - 'index.js'
  # Assets
  - 'assets/**'
