# Shared path filter definitions
# Used by path-filter.yml workflow for both PR-level and push-level checks
#
# NOTE: Do not add gitignored paths here (android/, ios/, pdb-*/, .env)
# They will never trigger since they're never committed.

shell:
  - '**/*.sh'
  - '.husky/**'
  - '.claude/hooks/**'

app:
  # Source code
  # NOTE: Negation patterns removed due to dorny/paths-filter bug
  # where !**/*.test.ts matches ALL non-test files including docs/
  # See: https://github.com/dorny/paths-filter/issues/97
  - 'app/**'
  - 'core/**'
  - 'ui/**'
  - 'infra/**'
  # Config files that affect the build
  - 'app.config.js'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - 'babel.config.cjs'
  - 'metro.config.cjs'
  - 'eas.json'
  - 'schema.prisma'
  - 'index.js'
  # Assets
  - 'assets/**'
