# Shared path filter definitions
# Used by path-filter.yml workflow for both PR-level and push-level checks
#
# NOTE: Do not add gitignored paths here (android/, ios/, pdb-*/, .env)
# They will never trigger since they're never committed.
#
# IMPORTANT: Do NOT use negation patterns (!) in dorny/paths-filter.
# They match "everything NOT matching pattern" rather than excluding.
# See: https://github.com/dorny/paths-filter/issues/97

shell:
  - '**/*.sh'
  - '.husky/**'
  - '.claude/hooks/**'

# Source code directories (triggers test job)
src:
  - 'app/**'
  - 'core/**'
  - 'ui/**'
  - 'infra/**'

# Test files only (used to detect test-only changes)
tests:
  - '**/*.spec.ts'
  - '**/*.test.ts'
  - '**/_tests_/**'
  - '**/fixtures/**'
  - '**/data-builders/**'
  - 'vitest.config.js'

# Config files that affect the build
config:
  - 'app.config.js'
  - 'package.json'
  - 'package-lock.json'
  - 'tsconfig.json'
  - 'babel.config.cjs'
  - 'metro.config.cjs'
  - 'eas.json'
  - 'schema.prisma'
  - 'index.js'
  - 'assets/**'
