#!/usr/bin/env bash
set -euo pipefail

# Detect the retro file generated by claude-code-action.
#
# Usage: ./scripts/detect-retro-file.sh <PR_NUMBER>
# Output: Sets retro_path in GITHUB_OUTPUT, or empty if not found / minimal.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/lib/colors.sh"

PR_NUMBER="${1:-}"
if [[ -z "$PR_NUMBER" ]]; then
  print_error "PR number is required"
  exit 1
fi

RETRO_FILE=$(find docs/retrospective -name "PR-${PR_NUMBER}-*-review-retro.md" -type f 2>/dev/null | head -1)

if [[ -z "$RETRO_FILE" ]]; then
  print_warning "No retro file found for PR #$PR_NUMBER — skipping commit and Slack"
  echo "retro_path=" >> "${GITHUB_OUTPUT:-/dev/null}"
  exit 0
fi

if grep -q "Minimal review activity" "$RETRO_FILE" 2>/dev/null; then
  print_info "Minimal review activity — skipping commit and Slack"
  echo "retro_path=" >> "${GITHUB_OUTPUT:-/dev/null}"
  exit 0
fi

print_success "Detected retro file: $RETRO_FILE"
echo "retro_path=$RETRO_FILE" >> "${GITHUB_OUTPUT:-/dev/null}"
