#!/bin/bash
# Generate ESM (.js) copies of CJS (.cjs) ESLint rules for OxLint JS plugins.
# Also generates oxlint-plugin-local-rules.js entry point.
#
# Usage: bash scripts/generate-esm-rules.sh
#
# The .cjs files are the source of truth (used by ESLint + tests).
# The .js files are generated artifacts (used by OxLint JS plugins).

set -euo pipefail

RULES_DIR="eslint-rules"
PLUGIN_FILE="oxlint-plugin-local-rules.js"

# --- Step 1: Convert each .cjs rule to .js (ESM) ---

echo "Generating ESM rules from CJS sources..."

# Clean existing generated .js files
rm -f "$RULES_DIR"/*.js

count=0
for cjs_file in "$RULES_DIR"/*.cjs; do
  # Skip test files
  case "$cjs_file" in *.spec.cjs|*.test.cjs) continue ;; esac

  basename=$(basename "$cjs_file" .cjs)
  js_file="$RULES_DIR/$basename.js"

  # Convert CJS to ESM:
  #   const X = require('Y') → import X from 'Y'
  #   module.exports = → export default
  sed \
    -e "s/^const \([a-zA-Z]*\) = require('\([^']*\)')/import \1 from '\2'/" \
    -e "s/^module\.exports = /export default /" \
    "$cjs_file" > "$js_file"

  count=$((count + 1))
done

echo "  Generated $count ESM rule files."

# --- Step 2: Generate oxlint-plugin-local-rules.js ---

echo "Generating $PLUGIN_FILE..."

# Collect all rule basenames (sorted for deterministic output)
rules=()
for cjs_file in "$RULES_DIR"/*.cjs; do
  case "$cjs_file" in *.spec.cjs|*.test.cjs) continue ;; esac
  rules+=("$(basename "$cjs_file" .cjs)")
done

# Convert kebab-case to camelCase for JS variable names
# Uses awk for portability (macOS sed lacks \U for uppercase)
kebab_to_camel() {
  echo "$1" | awk -F- '{for(i=1;i<=NF;i++){if(i==1){printf "%s",$i}else{printf "%s%s",toupper(substr($i,1,1)),substr($i,2)}}print ""}'
}

{
  echo "// Auto-generated by scripts/generate-esm-rules.sh — do not edit manually"

  # Import statements
  for rule in "${rules[@]}"; do
    varname=$(kebab_to_camel "$rule")
    echo "import $varname from './eslint-rules/$rule.js'"
  done

  echo ""
  echo "export default {"
  echo "  meta: { name: 'local-rules' },"
  echo "  rules: {"

  # Rule entries
  for rule in "${rules[@]}"; do
    varname=$(kebab_to_camel "$rule")
    echo "    '$rule': $varname,"
  done

  echo "  },"
  echo "}"
} > "$PLUGIN_FILE"

echo "  Generated $PLUGIN_FILE with ${#rules[@]} rules."

# --- Step 3: Verify no unconverted require() calls ---

if grep -l "require(" "$RULES_DIR"/*.js 2>/dev/null; then
  echo "ERROR: Unconverted require() found in generated files!" >&2
  exit 1
fi

# --- Step 4: Format generated files (best-effort, may fail during postinstall) ---

echo "Formatting generated files..."
if npx prettier --write "$RULES_DIR"/*.js "$PLUGIN_FILE" --log-level warn 2>/dev/null; then
  :
else
  echo "  Prettier not available, skipping formatting (files still usable)."
fi

echo "Done! Generated ${#rules[@]} ESM rules + plugin entry point."
