#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch=$(git branch --show-current)

if [ "$branch" = "main" ]; then
  echo "\033[0;35mDirect push to main branch is not allowed.\033[0m\n"
  exit 1
fi

yarn check:uncommitted && yarn test:cov
